/*
 * timer_Cfg.h
 *
 *  Created on: ??þ/??þ/????
 *      Author: batma
 */

#ifndef MCAL_TIMER_TIMER_CFG_H_
#define MCAL_TIMER_TIMER_CFG_H_

#define DISABLE			0
#define ENABLE			1

#define TOGGLE_MODE_OC	0
#define ClEAR_MODE_OC	1
#define SET_MODE_OC		2

#define INVERTING		0
#define NON_INVERTING	1

#define TOP_8BIT		1
#define TOP_9BIT		2
#define TOP_10BIT		3
#define TOP_OCRA		4
#define TOP_ICR			5

#define PRESCALER_NO	0
#define PRESCALER_8		8
#define PRESCALER_64	64
#define PRESCALER_256	256
#define PRESCALER_1024	1024
#define TIMER_OFF		5

#define TIMER1_TCNT1_TICKS		65536
#define TIMER1_NORMAL_MODE		0
#define TIMER1_CTC_OCA_MODE		1
#define TIMER1_CTC_OCB_MODE		2
#define TIMER1_PWM_FAST_OCA_MODE	3
#define TIMER1_PWM_FAST_OCB_MODE	4
#define TIMER1_PWM_PHASE_OCA_MODE	5
#define TIMER1_PWM_PHASE_OCB_MODE	6

#define TIMER1_PRESCALER		 			PRESCALER_256
#define TIMER1_INTERRUPT					DISABLE
#define TIMER1_TCNT_INTERRUPT				DISABLE
#define TIMER1_OCR_OCA_INTERRUPT			DISABLE
#define TIMER1_OCR_OCB_INTERRUPT			DISABLE
#define TIMER1_MODE_SELECT					TIMER1_PWM_FAST_OCA_MODE
#define TIMER1_FAST_PWM_MODE_SELECT			NON_INVERTING
#define TIMER1_PWM_FAST_A_MODE_TOP_SELECT	TOP_ICR
#define TIMER1_CTC_MODE_SELECT 				TOGGLE_MODE_OC



#endif /* MCAL_TIMER_TIMER_CFG_H_ */
